server: 
  port: 9999
spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: music-search
            uri: http://localhost:8082
            predicates:
            - Path=/search
            # 添加请求头断言，
            # 测试发送给网关，使用psotman或者HOPPSCOTCH,发送get请求http://localhost:9999/demo/hello，
            # 然后请求头放入Authorization，demo测试
            # - auth=authorization
            filters:
            - addResponseHeader=x-demo-id,123
            - log





# - Path=/demo/**